### ISSUE TITLE
Set Heat/Cool Mode based on a different temperature sensor.

### ISSUE THREAD

**Issue by ssarwa** [dlarrick/hass-kumo#148]
Currently you can set the heat / cool mode only based on its own temperature settings. There are instances where the unit needs to set up the mode based on a different sensor. This is possible in ecobee or nest thermostats but not Kumo. If there is a configuration that can be set based on this it will be great.

**Comment by barndawgie** [comment]
You can do this via Home Assistant automation, correct? It's just not a "native' feature of the hass-kumo integration?

Can you point to an example (e.g. in Ecobee Docs) on how you are doing this/what you're asking for?

**Comment by ssarwa** [comment]
Not sure how can you do this via Home Automation. The Kumo integration has mode as Heat, Cool and Heat/Cool. All these depend on its own temperature sensor. I want to be able to change this based on a different sensor.

Nest/Ecobee comes with additional temperature sensors that can be placed in various rooms and the Thermostat can be configured to use those sensors for the modes.

**Comment by EricE** [comment]
I personally use a Z-wave+ sensor in a room to get a better measurement of the temperature.  You then use a Home Assistant automation, either https://www.home-assistant.io/docs/automation/  or  Node-RED (which is what I use):  https://community.home-assistant.io/t/home-assistant-community-add-on-node-red/55023 to monitor the external temperature sensor and send commands to the Kumo integration.  I mostly use [Aeotec temperature sensors](https://aeotec.com/products/aeotec-aerq-sensor/) but there are a lot of vendors.

**Comment by AlteVerwischteZiege** [comment]
I find that the mini splits produce inaccurate temperature readings so I used the same approach as EricE, using the automation builder.  I am not the most gifted coder, so it runs some 630 lines to control the five zones and cut out the heat pumps and enable the Oil furnace at extreme low temps.  Below is a segment that uses the value of a templated sensor -sensor.avg_great_room_kitchen_temp - to control the mode of one of the heads.
```
    - conditions:
      - condition: state
        entity_id: input_select.heat_pump_status
        state: Heat
      sequence:
      - if:
        - condition: and
          conditions:
          - condition: state
            entity_id: input_boolean.climate_great_room_system_boolean
            state: 'on'
          - condition: state
            entity_id: input_boolean.great_room_hvac_active
            state: 'on'
          - condition: numeric_state
            entity_id: sensor.avg_great_room_kitchen_temp
            below: input_number.climate_target_temperature
        then:
        - service: climate.set_hvac_mode
          data:
            hvac_mode: heat
          target:
            entity_id: climate.greatroom
        - service: climate.set_temperature
          data:
            temperature: '{{ states(''input_number.climate_target_temperature'')|
              float(0) }}'
          target:
            entity_id: climate.greatroom
        - service: counter.increment
          data: {}
          target:
            entity_id: counter.counter_great_room
        else:
        - service: climate.set_hvac_mode
          data:
            hvac_mode: 'off'
          target:
            entity_id: climate.greatroom
```

I hope that is helpful
