### ISSUE TITLE
After upgrade to 2024.8.2, unable to use climate.turn_off or turn_on

### ISSUE THREAD

**Issue by OmenWild** [dlarrick/hass-kumo#164]
I have automations with:
```yaml
- service: climate.turn_off
  entity_id: climate.computer_room
```
But after upgrading to 2024.8.2 I get the following error in the log: 
`Entity climate.computer_room does not support this service.`

Additionally, when I try to use `Climate: Turn off` from Developer Tools -> Actions, it shows `No matching entities found` when I try to add an entity. `Climate: Turn on` shows the same lack of entites, but `Climate: Set HVAC mode` shows all my minisplits, matching what I am seeing in the automations.

My current workaround is this:
```yaml
- action: climate.set_hvac_mode
  target:
    entity_id: climate.computer_room
  data:
    hvac_mode: "off"
```

I am currently running the latest released version of this plugin installed with HACS.
