### ISSUE TITLE
esp32 alternative discussion

### ISSUE THREAD

**Issue by dlarrick** [dlarrick/hass-kumo#190]
Please use this sub-issue to discuss using esp32 as an alternative to Kumo WiFi adapters.

**Comment by omriasta** [comment]
https://github.com/dlarrick/hass-kumo/issues/189#issuecomment-2787099207
Thanks @joergbattermann I already placed my order and got the ATOM LITE ESP32 DEV KIT from digikey which appears a bit different from the S3 lite....I chose this one as it said tested on the main project page..... 
Maybe the others can benefit from your spares. I am curious how difficult it is to pop off the connector and replace it with the CN105 connector....that is the part that intimidates me most....I'm no good with any solder so I was happy to see that this was possible just not sure how hard it is...

**Comment by matthewhadley** [comment]
Reference link found for implementing local control with ESP32https://www.reddit.com/r/homeassistant/comments/1jk06x6/success_esphome_dumb_mitsubishi_mini_split_heat/

**Comment by joergbattermann** [comment]
> [#189 (comment)](https://github.com/dlarrick/hass-kumo/issues/189#issuecomment-2787099207) Thanks [@joergbattermann](https://github.com/joergbattermann) I already placed my order and got the ATOM LITE ESP32 DEV KIT from digikey which appears a bit different from the S3 lite....I chose this one as it said tested on the main project page..... Maybe the others can benefit from your spares. I am curious how difficult it is to pop off the connector and replace it with the CN105 connector....that is the part that intimidates me most....I'm no good with any solder so I was happy to see that this was possible just not sure how hard it is...

Sure thing and oh that connector part is super easy. You can get these PAP-05V-S connectors for cheap at Mouser Digikey as well and the reason why I [ordered these Grove cables](https://shop.m5stack.com/products/4pin-buckled-grove-cable) along is that a) these Atom controllers use these / come with a port on them.. and while these pre-made cables have Grove connectors on both ends, the crimped ends _inside_ those Grove connectors fit into the PAP-05V-S ones just fine & have the correct header and all that. So you don't have to crimp those 2.5-something millimeter heads onto a wire yourself (I'm not that old but yeah.. those _are_ small).

Anyway, what I did was take a [wire snipper with a good, small precision head ](https://www.knipex-tools.com/products/electronics-pliers/knipex-super-knips-electronics-pliers-esd) and carefully cut the outer edges of the grove connector open on both sides, like there/this:

![Image](https://github.com/user-attachments/assets/b011d85f-78ca-42bb-bc4c-5f1090aedfc5)

... then snipped the supporting / dividing ones in between the leads:

![Image](https://github.com/user-attachments/assets/2b11b47d-e40c-432a-ab5d-313b30775b08)


.. aaand then you can just carefully lift that entire piece of plastic on top carefully up & away.. and take the wires out.

The wires themselves are each crimped like that:

![Image](https://github.com/user-attachments/assets/8551e41c-3006-4599-bd1b-dab572509d2d)

.. you just take one of the PAP-05-S's...

![Image](https://github.com/user-attachments/assets/f387f64a-2973-4d3e-a64d-3ad400ecf7dd)

and insert the wires like this (again, make sure to follow the order as per image at https://github.com/echavet/MitsubishiCN105ESPHome/discussions/83#discussion-6570366):

![Image](https://github.com/user-attachments/assets/7df54cf6-36f7-4848-812a-e8184f95b054)

This can feel a bit tricky at first as the PAP-05-S connector has a small lip on the bottom which you have to overcome when pushing the wires in but I've found that when you come in at a slight angle 'from below' they go in just fine. Just pull back straight once it's all the way in and it should stay in / can't be pulled back out anymore.

The only other thing to make sure is the correct wire/ports to connect between both ends of the cable and headers. The CN105/PAP-05V-S side with the tiny triangle/pointer (see faintly at i.e. https://github.com/echavet/MitsubishiCN105ESPHome/discussions/83#discussion-6570366) is a 12V lead/port on the CN105 connection which would fry your ESP32 controller, so you should not connect that (nor is there a reason for it).. so it should look like that / see the empty port on the CN105 end:

![Image](https://github.com/user-attachments/assets/c934d350-e184-4564-b12a-2344becde1d1)

**Comment by omriasta** [comment]
This is perfect. I think I can manage this....I probably should have ordered more spares but hopefully I don't mess up too much...

**Comment by joergbattermann** [comment]
> This is perfect. I think I can manage this....I probably should have ordered more spares but hopefully I don't mess up too much...

Just cut/snip slowly and you'll be fine. If you need a couple more of those JST connectors or maybe one or two spare cables after you ran out of yours just holla and I can throw them in an envelope and send them your ways.

**Comment by omriasta** [comment]
> > This is perfect. I think I can manage this....I probably should have ordered more spares but hopefully I don't mess up too much...
> 
> Just cut/snip slowly and you'll be fine. If you need a couple more of those JST connectors or maybe one or two spare cables after you ran out of yours just holla and I can throw them in an envelope and send them your ways.

Very much appreciated....I'll go slow!

**Comment by matthewhadley** [comment]
Thank you @joergbattermann! I just ordered the airzone port splitter and will come back here when I attempt things.

In my setup I currently have the kumo cloud adapter and a separate redlink wireless remote controller on the wall - it looks like I should be able to integrate the esp32 setup (I already have some m5 units on hand). I noticed in [this reddit post](https://www.reddit.com/r/homeassistant/comments/1hz1f5c/mitsibushi_heat_pump_with_mhk2_esp32_controlle/) someone pointed out a particular order to chain the devices for things to work.

**Comment by joergbattermann** [comment]
> Thank you [@joergbattermann](https://github.com/joergbattermann)! I just ordered the airzone port splitter and will come back here when I attempt things.
> 
> In my setup I currently have the kumo cloud adapter and a separate redlink wireless remote controller on the wall - it looks like I should be able to integrate the esp32 setup (I already have some m5 units on hand). I noticed in [this reddit post](https://www.reddit.com/r/homeassistant/comments/1hz1f5c/mitsibushi_heat_pump_with_mhk2_esp32_controlle/) someone pointed out a particular order to chain the devices for things to work.

👍🏻 FYI, I have it set it up a bit different than that reddit post @matthewhadley - I have the Airzone port splitter plugged into the CN105 port on the indoor unit's motherboard where the WF-2 used to be connected into.. and then used one of the Airzone's two 'split' ports and connected said Kumo Cloud / WF-2 adapter into, which then has the Redlink MIFH2 for the MHK2 daisy chained onwards, and the ESP32 controller is plugged into the second Airzone port.

Anyway, it works perfectly fine - I can make changes with either of the three quasi-controllers and those changes appear on all two other devices / the comfort app so there doesn't seem too much "magic" / logic going on.

If you need any help with cable or HA/ESPHome configuration, just let me know!

**Comment by matthewhadley** [comment]
I have rigged everything up and have a setup that seems to be working, but it only seems to work in one configuration of the 3 devices...

First, in my testing I noticed that I could trim some of the grove wire port casing (that's attached to the M5 Atom S3 Lite) and it fits into the Air Zone CN105 just fine (note I am avoiding the 12v pin)

![Image](https://github.com/user-attachments/assets/208cc7f8-1875-43d9-9ff7-35f88225ba73)

Here is the yaml I am using for my M5 Atom S3 Lite

```yaml
external_components:
  - source: github://echavet/MitsubishiCN105ESPHome
  
esphome:
  name: m5-atom-s3l-minisplit-34b7da
  friendly_name: M5 Atom S3 Lite MiniSplit 34b7da

esp32:
  board: esp32-s3-devkitc-1         
  framework:
    type: arduino    
    version: latest

api:
  encryption:
    key: !secret esphome_home_assistant_encryption_key

ota:
  - platform: esphome
    password: !secret esphome_ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:

uart:
  id: HP_UART
  baud_rate: 2400
  tx_pin: GPIO1
  rx_pin: GPIO2

sensor:
  - platform: uptime
    name: Uptime

light:
  - platform: esp32_rmt_led_strip
    rgb_order: GRB
    pin: 35
    num_leds: 4
    # RMT 0 channels will be occupied by IR
    rmt_channel: 1
    chipset: ws2812
    id: led
    name: "LED"

#G41=Button
binary_sensor:
  - platform: gpio
    name: Button
    pin:
      number: GPIO41
      inverted: true
      mode:
        input: true
        pullup: true
    filters:
      - delayed_off: 10ms
    on_press:
      then:
        - logger.log: Button Pressed

climate:
  - platform: cn105
    id: hp
    name: "MiniSplit"
    update_interval: 2s 
```

Here is how the 3 devices are connected:

```
motherboard CN105 port -> splitter  -> (ACC port) Redlink MIFH2
			             -> (AZ port) Kumo Cloud -> M5 Atom S3 Lite

```
![Image](https://github.com/user-attachments/assets/aaddd4a6-08e2-40ec-aa66-c5733ce263dc)

In this setup, the Redlink thermostat, Kumo integration and the ESP32 device all seem to be able to control the mini split.

I have **not** been able to find a setup where I can remove the Kumo Cloud and just have the Redlink Wall Thermostat and M5 Atom S3 Lite device - when I have the M5 Atom S3 Lite device directly in the AZ port the logs would just show `[16:36:24][I][CN105:177]: We think Heatpump is not connected anymore..`. I tried swapping around (M5 Atom S3 Lite into the ACC port) with the same outcome.

So my setup is currently the same as https://www.reddit.com/r/homeassistant/comments/1hz1f5c/mitsibushi_heat_pump_with_mhk2_esp32_controlle/

@joergbattermann when I try the setup you described https://github.com/dlarrick/hass-kumo/issues/190#issuecomment-2787496044 the M5 Atom S3 Lite can't connect to the heat pump 🤷 

Another thing to note is that the Kumo integration now reports the Current Humidity as `Unknown`.

I'm monitoring how things are working - when I tried different configurations of the devices I noticed the Mini Split unit went into Cool mode, but to 85 degrees F - maybe something to do with me plugging things in and out...
