### ISSUE TITLE
humidity sensor?

### ISSUE THREAD

**Issue by momoz** [dlarrick/hass-kumo#69]
Is there a way to expose the humidity?   my unit reports it in the app and the wireless module.

thx

**Comment by dlarrick** [comment]
If you have a sensor paired to your indoor unit, the humidity is reported as an attribute on the main climate unit as "current_humidity". You can set up a template sensor to extract this attribute to a sensor entity. Here's mine:
```
      loft_humidity:
        friendly_name: 'Loft Humidity'
        unit_of_measurement: "%"
        value_template: >
          {{ state_attr('climate.loft','current_humidity') }}
```
If you don't have such an attribute, feel free to reopen this issue with more details about your setup.
